export enum DoctorSpecialization {
  GENERAL_PRACTITIONER = 'General Practitioner',
  CARDIOLOGIST = 'Cardiologist',
  NEUROLOGIST = 'Neurologist',
  OBSTETRICIAN = 'Obstetrician',
  PEDIATRICIAN = 'Pediatrician',
  DERMATOLOGIST = 'Dermatologist',
  PSYCHIATRIST = 'Psychiatrist',
  CLINICAL_PSYCHOLOGIST = 'Clinical Psychologist',
  OPHTHALMOLOGIST = 'Ophthalmologist',
  AUDIOLOGIST = 'Audiologist',
  ORTHOPEDIST = 'Orthopedist',
  PLASTIC_SURGEON = 'Plastic Surgeon',
  ENDOCRINOLOGIST = 'Endocrinologist',
  IMMUNOLOGIST = 'Immunologist',
  ALLERGIST = 'Allergist',
  PATHOLOGIST = 'Pathologist',
  PUBLIC_HEALTH_SPECIALIST = 'Public Health Specialist',
}
